-- データベース作成
CREATE DATABASE IF NOT EXISTS pos_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pos_db;

-- 商品マスタテーブル
CREATE TABLE products (
    PRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE CHAR(13) UNIQUE NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRICE INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 取引テーブル
CREATE TABLE transactions (
    TRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EMP_CD CHAR(10) DEFAULT '9999999999',
    STORE_CD CHAR(5) DEFAULT '30',
    POS_NO CHAR(3) DEFAULT '90',
    TOTAL_AMT INT DEFAULT 0
);

-- 取引明細テーブル
CREATE TABLE transaction_items (
    TRD_ID INT,
    DTL_ID INT,
    PRD_ID INT,
    PRD_CODE CHAR(13),
    PRD_NAME VARCHAR(50),
    PRD_PRICE INT,
    PRIMARY KEY (TRD_ID, DTL_ID),
    FOREIGN KEY (TRD_ID) REFERENCES transactions(TRD_ID),
    FOREIGN KEY (PRD_ID) REFERENCES products(PRD_ID)
);

-- サンプルデータ投入
INSERT INTO products (CODE, NAME, PRICE) VALUES
('1234567890', 'おーいお茶', 150),
('2345678901', 'ソフラン', 300),
('3456789012', '福島産うりん菓', 185),
('4567890123', 'タイガー島ブラン', 200),
('5678901234', '西谷サイダー', 160);